import { Link } from 'react-router-dom';
import {
    FaBolt, FaChevronRight, FaShieldAlt,
    FaUsers, FaFire, FaClock, FaDiceD20
} from 'react-icons/fa';
import { useState } from 'react';
import { useTheme } from './shared/SiteSettingsContext';
import { useSiteSettings } from './shared/SiteSettingsContext';

// Create Card Sampler
import { PlayerSearchInput } from './customs/PlayerSearchInput';
import { CardItem } from './cards/CardItem';
import CardCommand from './cards/card_elements/CardCommand';
import CardChart from './cards/card_elements/CardChart';
import type { ShowdownBotCard } from '../api/showdownBotCard';

export default function Home() {

    // State
    const [searchQuery, _] = useState<string>('');
    const [selectedCard, setSelectedCard] = useState<ShowdownBotCard | null>(null);
    const { isDark } = useTheme();
    const { userShowdownSet } = useSiteSettings();

    return (
        <div
            className={`
                px-8
                space-y-8
                ${isDark 
                    ? 'bg-gradient-to-br from-black via-neutral-900 to-neutral-950' 
                    : 'bg-gradient-to-br from-white via-neutral-100 to-neutral-200'
                }
            `}>

            {/* Hero Section */}
            <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between py-10 gap-10">

                {/* Left: Text and Actions */}
                <div className="flex-1 flex flex-col gap-4 items-start">
                    <span className={`inline-flex items-center gap-2 px-4 py-1 rounded-full text-sm font-semibold mb-2 ${isDark ? 'bg-white/10' : 'bg-black/10'}`}>
                        <FaBolt className="text-yellow-400" /> Custom Showdown cards in seconds
                    </span>
                    <h1 className="text-4xl md:text-5xl font-extrabold leading-tight">
                        Digital Cards that Play Ball.
                    </h1>
                    <p className={`text-lg max-w-xl leading-6 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                        Enter a player and season. We turn real stats into a simulated card for the iconic 20-sided dice game — ready to share, use in your league, or just admire.
                    </p>
                    <form className={`rounded-2xl p-6 flex flex-col gap-4 w-full ${isDark ? 'bg-neutral-900/80 border border-neutral-800' : 'bg-white/80 border border-neutral-200'}`}>
                        <PlayerSearchInput label='Search for a player' value={searchQuery} onChange={(e) => {}} />
                        <CardItem card={selectedCard} onClick={() => {}}/>
                    </form>
                    <div className="flex gap-4 mt-2">
                        <Link to="/customs" className={`flex items-center gap-2 px-6 py-3 rounded-xl text-lg font-semibold shadow hover:bg-neutral-200 transition ${isDark ? 'bg-white text-black' : 'bg-black text-white'}`}>
                            Build your Own <FaChevronRight />
                        </Link>
                        <Link to="/explore" className={`flex items-center gap-2 px-6 py-3 rounded-xl text-lg font-semibold shadow transition ${isDark ? 'bg-neutral-900 border border-neutral-700 text-white hover:bg-neutral-800' : 'bg-white border border-neutral-300 text-black hover:bg-neutral-100'}`}>
                            Explore Cards <FaChevronRight />
                        </Link>
                        {/* <Link to="/rules" className={`flex items-center gap-2 px-6 py-3 rounded-xl text-lg font-semibold shadow transition ${isDark ? 'bg-neutral-900 border border-neutral-700 text-white hover:bg-neutral-800' : 'bg-white border border-neutral-300 text-black hover:bg-neutral-100'}`}>
                            I'm new to Showdown <FaChevronRight />
                        </Link> */}
                    </div>
                </div>

                {/* Right: Random Card of the Day */}
                <div className="flex-1 flex flex-col items-center md:items-end w-full">
                    <div className={`rounded-3xl p-6 w-full max-w-md min-h-[400px] flex flex-col relative gap-1 ${isDark ? 'bg-neutral-900/80 border border-neutral-800' : 'bg-white/80 border border-neutral-200'}`}>
                        <div className="flex justify-between items-center mb-2">
                            <span className={`text-lg font-semibold ${isDark ? 'text-white/80' : 'text-black/80'}`}>Card of the Day</span>
                            <span className={`text-xs ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Generated by the Community</span>
                        </div>
                        <div className="flex-1 flex flex-col justify-center items-center gap-4">
                            <img src={`/images/blank_players/blankplayer-${userShowdownSet}-dark.png`} alt="Sample Showdown Card" className="min-h-64 max-h-124 rounded-lg shadow-lg object-contain" />
                        </div>
                        <div className={`left-4 right-4 text-xs text-left ${isDark ? 'text-neutral-500' : 'text-neutral-400'}`}>
                            Showing 2004 Mike Piazza • Using the 2001 Set
                        </div>
                    </div>
                </div>
            </div>

            {/* How it Works */}
            <div className="max-w-7xl mx-auto py-6 border-t border-form-element">
                <h2 className="text-3xl font-bold mb-8">How to Play</h2>
                
                {/* Steps: Side by Side on md+ */}
                <div className="grid md:grid-cols-2 gap-8 mb-12">
                    {/* Step 1: The Pitch */}
                    <div>
                        <div className="mb-3">
                            <span className={`text-sm font-semibold uppercase tracking-wide ${isDark ? 'text-red-400' : 'text-red-600'}`}>Step 1</span>
                            <h3 className="text-xl font-bold mt-1">The Pitch</h3>
                            <p className={`text-sm mt-1 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Pitcher rolls to see who gets the advantage</p>
                        </div>

                        <div className={`text-sm space-y-1.5 mb-3 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                            <div className="flex items-start gap-2">
                                <span className="text-red-500 font-bold">•</span>
                                <span>Pitcher's total <strong>(Control + Dice Roll)</strong> higher = Pitcher's advantage</span>
                            </div>
                            <div className="flex items-start gap-2">
                                <span className="text-blue-500 font-bold">•</span>
                                <span>Pitcher's total lower or tied = Batter's advantage</span>
                            </div>
                        </div>
                        
                        <div className={`rounded-xl p-4 ${isDark ? 'bg-neutral-800/50 border border-neutral-700' : 'bg-neutral-100 border border-neutral-300'}`}>
                            <div className='flex items-center justify-center gap-3'>
                                <div className='flex flex-col items-center gap-1'>
                                    <CardCommand isPitcher={true} primaryColor="rgb(200, 16, 46)" secondaryColor="rgb(255, 255, 255)" command={4} team="BOS" className="w-10 h-10 shrink-0" />
                                    <span className='text-[10px] font-bold text-tertiary'>Control</span>
                                </div>
                                <span className='text-lg font-bold'>+</span>
                                <div className='flex flex-col items-center gap-1'>
                                    <FaDiceD20 className="text-gray-500 w-10 h-10" />
                                    <span className='text-[10px] font-bold text-tertiary'>Dice Roll</span>
                                </div>
                                <span className={`text-xs font-bold uppercase px-3 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>vs</span>
                                <div className='flex flex-col items-center gap-1'>
                                    <CardCommand isPitcher={false} primaryColor="rgb(12, 35, 64)" secondaryColor="rgb(255, 255, 255)" command={8} team="NYY" className="w-10 h-10 shrink-0" />
                                    <span className='text-[10px] font-bold text-tertiary'>On-Base</span>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>

                    {/* Step 2: The Swing */}
                    <div>
                        <div className="mb-3">
                            <span className={`text-sm font-semibold uppercase tracking-wide ${isDark ? 'text-blue-400' : 'text-blue-600'}`}>Step 2</span>
                            <h3 className="text-xl font-bold mt-1">The Swing</h3>
                            <p className={`text-sm mt-1 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Batter rolls to see what happens</p>
                        </div>
                        
                        <div className={`text-sm space-y-1.5 mb-3 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                            <div className="flex items-start gap-2">
                                <span className="text-red-500 font-bold">•</span>
                                <span><strong>Pitcher's advantage:</strong> Find result on pitcher's chart</span>
                            </div>
                            <div className="flex items-start gap-2">
                                <span className="text-blue-500 font-bold">•</span>
                                <span><strong>Batter's advantage:</strong> Find result on batter's chart</span>
                            </div>
                        </div>
                        
                        <div className={`rounded-xl p-3 ${isDark ? 'bg-neutral-800/50 border border-neutral-700' : 'bg-neutral-100 border border-neutral-300'}`}>
                            <div className="flex items-start gap-3">
                                <div className='flex flex-col items-center gap-1 pt-2'>
                                    <FaDiceD20 className="text-gray-500 w-8 h-8" />
                                    <span className='text-[10px] font-bold text-tertiary'>Roll</span>
                                </div>
                                <div className='flex flex-col items-center justify-center gap-1 pt-3'>
                                    <FaChevronRight className={`${isDark ? 'text-neutral-400' : 'text-neutral-600'}`} />
                                    <span className={`text-[9px] font-semibold uppercase ${isDark ? 'text-neutral-500' : 'text-neutral-600'}`}>Find</span>
                                </div>
                                <div className="flex-1">
                                    <CardChart 
                                        chartRanges={{"SO":"1-2","GB":"3-4","FB":"5-6","BB":"7-8","1B":"9-15","1B+":"-","2B":"16-17","3B":"18","HR":`${['2000', '2001', 'CLASSIC'].includes(userShowdownSet)? '19-20' : '19+'}`}} 
                                        showdownSet={userShowdownSet || '2001'}
                                        primaryColor="rgb(12, 35, 64)"
                                        secondaryColor="rgb(255, 255, 255)"
                                        team="NYY"
                                        cellClassName="min-w-9"
                                        className="mb-1"
                                    />
                                    <p className={`text-[10px] ${isDark ? 'text-neutral-500' : 'text-neutral-600'}`}>Example: Roll 16 = Double!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                {/* Next Steps and Why it Works */}
                <div className="grid md:grid-cols-2 gap-8 mb-12">
                    {/* The Rest */}
                    <div>
                        <h2 className="text-2xl font-bold mb-4">Play out the Game</h2>
                        <ul className="space-y-2 mb-4">
                            <li className={`flex items-start gap-2 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                                <span className="text-primary font-bold mt-0.5">•</span>
                                <span><strong>Build your team:</strong> <span className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>Draft players within a salary cap budget (or just pick your favorite all-stars!)</span></span>
                            </li>
                            <li className={`flex items-start gap-2 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                                <span className="text-primary font-bold mt-0.5">•</span>
                                <span><strong>Play 9 innings:</strong> <span className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>Alternate pitching and batting through 9 innings</span></span>
                            </li>
                            <li className={`flex items-start gap-2 ${isDark ? 'text-neutral-300' : 'text-neutral-700'}`}>
                                <span className="text-primary font-bold mt-0.5">•</span>
                                <span><strong>Advanced Gameplay:</strong> <span className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>Incorporate baserunning, fielding, and strategic decisions</span></span>
                            </li>
                        </ul>
                        {/* <Link to="/rules" className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl font-semibold transition ${isDark ? 'bg-neutral-900 border border-neutral-700 text-white hover:bg-neutral-800' : 'bg-white border border-neutral-300 text-black hover:bg-neutral-100'}`}>
                            Learn more about gameplay <FaChevronRight />
                        </Link> */}
                    </div>

                    {/* Why it works */}
                    <div className="max-w-3xl mx-auto">
                        <h2 className="text-2xl font-bold mb-4">Why it works</h2>
                        <ul className="space-y-3 mb-4">
                            <li className="flex items-center gap-2"><FaDiceD20 className="text-primary" /> <span>20-sided dice system <span className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>— Every at-bat is different to the randomness of a dice roll.</span></span></li>
                            <li className="flex items-center gap-2"><FaShieldAlt className="text-primary" /> <span>Real stats, simulated play <span className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>— Players perform like they did in their actual season.</span></span></li>
                        </ul>
                        <div className={`rounded-xl p-4 text-sm ${isDark ? 'bg-neutral-800/80 text-neutral-300' : 'bg-neutral-200/80 text-neutral-700'}`}>
                            <div className="font-semibold mb-1">The beauty of Showdown</div>
                            <div className={isDark ? 'text-neutral-400' : 'text-neutral-600'}>"Dice rolls meet baseball stats. Fast-paced strategy with authentic player performance."</div>
                        </div>
                    </div>
                </div>
                
            </div>

            {/* Explore Section */}
            <div className="max-w-7xl mx-auto py-6 border-t border-form-element">
                <div className="flex justify-between items-center mb-6">
                    <h2 className="text-2xl font-bold">Explore</h2>
                    <Link to="/explore" className={`flex items-center gap-2 px-4 py-2 rounded-xl font-semibold transition ${isDark ? 'bg-neutral-900 border border-neutral-700 text-white hover:bg-neutral-800' : 'bg-white border border-neutral-300 text-black hover:bg-neutral-100'}`}>
                        Open Explore <FaChevronRight />
                    </Link>
                </div>
                <p className={`mb-6 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Give new users something to click immediately: trending cards, new builds, and a few curated collections.</p>
                <div className="grid md:grid-cols-3 gap-6">
                    <div className={`rounded-2xl p-6 min-h-[180px] ${isDark ? 'bg-neutral-900/80 border border-neutral-800' : 'bg-white/80 border border-neutral-200'}`}>
                        <div className="font-semibold mb-2 flex items-center gap-2"><FaFire className="text-red-500" /> Trending this week</div>
                        <div className={`text-sm mb-2 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Most-generated players and seasons.</div>
                        <div className={`rounded-lg h-16 ${isDark ? 'bg-neutral-800' : 'bg-neutral-200'}`} />
                    </div>
                    <div className={`rounded-2xl p-6 min-h-[180px] ${isDark ? 'bg-neutral-900/80 border border-neutral-800' : 'bg-white/80 border border-neutral-200'}`}>
                        <div className="font-semibold mb-2 flex items-center gap-2"><FaClock className="text-yellow-400" /> Live cards</div>
                        <div className={`text-sm mb-2 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Real-time updates during games.</div>
                        <div className={`rounded-lg h-16 ${isDark ? 'bg-neutral-800' : 'bg-neutral-200'}`} />
                    </div>
                    <div className={`rounded-2xl p-6 min-h-[180px] ${isDark ? 'bg-neutral-900/80 border border-neutral-800' : 'bg-white/80 border border-neutral-200'}`}>
                        <div className="font-semibold mb-2 flex items-center gap-2"><FaUsers className="text-primary" /> Creator picks</div>
                        <div className={`text-sm mb-2 ${isDark ? 'text-neutral-400' : 'text-neutral-600'}`}>Curated sets and fun themes.</div>
                        <div className={`rounded-lg h-16 ${isDark ? 'bg-neutral-800' : 'bg-neutral-200'}`} />
                    </div>
                </div>
            </div>
        </div>
    );
}
