from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum

class StandingsType(str, Enum):
    REGULAR_SEASON = "REGULAR_SEASON"
    WILD_CARD = "WILD_CARD"
    DIVISION_LEADERS = "DIVISION_LEADERS"
    WILD_CARD_WITH_LEADERS = "WILD_CARD_WITH_LEADERS"
    FIRST_HALF = "FIRST_HALF"
    SECOND_HALF = "SECOND_HALF"
    SPRING_TRAINING = "SPRING_TRAINING"
    POSTSEASON = "POSTSEASON"
    BY_DIVISION = "BY_DIVISION"
    BY_CONFERENCE = "BY_CONFERENCE"
    BY_LEAGUE = "BY_LEAGUE"
    BY_ORGANIZATION = "BY_ORGANIZATION"
    CURRENT_HALF = "CURRENT_HALF"
